import Head from "next/head";

import SliderPortfolio from "@/shared/components/SliderHome";

export default function Home() {
  return (
    <>
      <Head>
        <title>Oye Ricky</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="icon"
          href="https://img.icons8.com/plasticine/512/rick-sanchez.png"
        />
      </Head>
      <main>
        <div id="app">
          <SliderPortfolio />
        </div>
      </main>
    </>
  );
}
